import type { AppInstance } from '../http/app.js';

export interface SDKGeneratorOptions {
  baseUrl?: string;
  output?: string;
}

export function generateSDK(app: AppInstance, options: SDKGeneratorOptions = {}) {
  const { modules } = app;
  const baseUrl = options.baseUrl || 'http://localhost:3000';

  let code = `/**
 * V12 SDK - Autogenerated
 */

export interface RequestOptions {
  headers?: Record<string, string>;
  params?: Record<string, any>;
  query?: Record<string, any>;
  body?: any;
}

export class V12Client {
  constructor(private baseUrl: string = '${baseUrl}') {}

  private async request<T>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    let url = \`\${this.baseUrl}\${path}\`;
    
    if (options.params) {
      for (const [key, value] of Object.entries(options.params)) {
        url = url.replace(\`:\${key}\`, String(value));
      }
    }

    if (options.query) {
      const searchParams = new URLSearchParams();
      for (const [key, value] of Object.entries(options.query)) {
        if (value !== undefined) searchParams.append(key, String(value));
      }
      const qs = searchParams.toString();
      if (qs) url += \`?\${qs}\`;
    }

    const response = await fetch(url, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });

    const result = await response.json();
    if (!response.ok) {
      throw new Error(result.message || 'Request failed');
    }

    return result.data;
  }

`;

  for (const module of modules) {
    const moduleName = module.name.toLowerCase();
    code += `  public readonly ${moduleName} = {\n`;

    const prefix = [module.prefix ?? `/${module.name}`, module.routes?.prefix]
      .filter(Boolean)
      .join('');

    for (const route of module.routes?.routes ?? []) {
      const methodName = route.path === '/' || route.path === '' 
        ? route.method.toLowerCase() 
        : route.path.replace(/\//g, '_').replace(/:/g, '').replace(/^_/, '').toLowerCase() + '_' + route.method.toLowerCase();
      
      const cleanMethodName = methodName.replace(/[^a-zA-Z0-0_]/g, '');
      const fullPath = `${prefix}${route.path}`;

      const bodyType = zodToTs(route.schema?.body);
      const queryType = zodToTs(route.schema?.querystring);
      const paramsType = zodToTs(route.schema?.params);
      const responseType = zodToTs(route.schema?.response);

      code += `    /**
     * ${route.method} ${fullPath}
     */
    ${cleanMethodName}: (options: {
      body${bodyType === 'any' ? '?' : ''}: ${bodyType};
      query${queryType === 'any' ? '?' : ''}: ${queryType};
      params${paramsType === 'any' ? '?' : ''}: ${paramsType};
      headers?: Record<string, string>;
    }${bodyType === 'any' && queryType === 'any' && paramsType === 'any' ? ' = {}' : ''}) => this.request<${responseType}>('${route.method}', '${fullPath}', options),\n\n`;
    }

    code += `  };\n\n`;
  }

  code += `}\n\n`;
  code += `function zodToTs(schema: any): string {
  if (!schema) return 'any';
  const type = schema._def?.typeName;
  switch (type) {
    case 'ZodString': return 'string';
    case 'ZodNumber': return 'number';
    case 'ZodBoolean': return 'boolean';
    case 'ZodObject':
      const shape = schema._def.shape();
      const props = Object.entries(shape)
        .map(([key, value]: [string, any]) => {
          const isOptional = value._def.typeName === 'ZodOptional';
          return \`\${key}\${isOptional ? '?' : ''}: \${zodToTs(value)}\`;
        })
        .join('; ');
      return \`{ \${props} }\`;
    case 'ZodArray':
      return \`\${zodToTs(schema._def.type)}[]\`;
    case 'ZodOptional':
      return zodToTs(schema._def.innerType);
    case 'ZodNullable':
      return \`\${zodToTs(schema._def.innerType)} | null\`;
    case 'ZodEnum':
      return schema._def.values.map((v: any) => \`'\${v}'\`).join(' | ');
    default: return 'any';
  }
}
`;

  return code;
}

function zodToTs(schema: any): string {
  if (!schema) return 'any';
  const type = schema._def?.typeName;
  switch (type) {
    case 'ZodString': return 'string';
    case 'ZodNumber': return 'number';
    case 'ZodBoolean': return 'boolean';
    case 'ZodObject':
      const shape = schema._def.shape();
      const props = Object.entries(shape)
        .map(([key, value]: [string, any]) => {
          const isOptional = value._def.typeName === 'ZodOptional';
          return `${key}${isOptional ? '?' : ''}: ${zodToTs(value)}`;
        })
        .join('; ');
      return `{ ${props} }`;
    case 'ZodArray':
      return `${zodToTs(schema._def.type)}[]`;
    case 'ZodOptional':
      return zodToTs(schema._def.innerType);
    case 'ZodNullable':
      return `${zodToTs(schema._def.innerType)} | null`;
    case 'ZodEnum':
      return schema._def.values.map((v: any) => `'${v}'`).join(' | ');
    default: return 'any';
  }
}
